print('=====Desafio 5=====')
a = int(input('Digite um número inteiro:'))
print('Você digitou o número {}'.format(a), end=', ')
print('seu antecessor é {}'.format(a-1), end=' e ')
print('seu sucessor é {}'.format(a+1))