print('---DESAFIO PYTHON 4 ---')
print('CHEFÃO >:)')
palavra = input('Digite algo: ')
print('Você escreveu' ,  palavra)
print('Ele é númerico?', palavra.isnumeric())
print('É do alfabeto?', palavra.isalpha())
print('É ascii?', palavra.isascii())
print('É um digito?', palavra.isdigit())
print('Tá em lowercase?', palavra.islower())
print('É um decimal?', palavra.isdecimal())
print('Dá pra escrever um identificador no código?', palavra.isidentifier())
print('Dá pra imprimir?', palavra.isprintable())
print('É um espaço?', palavra.isspace())
print('Tá tudo em maiusculo?', palavra.isupper())
print(type(palavra))
